controller_list:
  - name: hiwin_6dot
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j_0001
      - j_0102
      - j_0203
      - j_0304
      - j_0405
      - j_0506